project_id = "vpojvymsladjbgeppglg"

[functions.extract-questions]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.translate-questions]
verify_jwt = false

[functions.start-exam]
verify_jwt = false

[functions.grade-exam]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.grant-free-access]
verify_jwt = false

[functions.send-access-email]
verify_jwt = false
